ERROR - 2024-10-16 15:23:14 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido.  in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('arturosaiza.com', 'ugsjwgu5z7wgt', 'guarache', 'dbhggkubvmugoy', 3306, '', 0)
#2 C:\laragon\www\fotobook\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\fotobook\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\laragon\www\fotobook\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\fotobook\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
#7 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
#8 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
#9 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido.  in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('arturosaiza.com', 'ugsjwgu5z7wgt', 'guarache', 'dbhggkubvmugoy', 3306, '', 0)
#1 C:\laragon\www\fotobook\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\fotobook\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\fotobook\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\fotobook\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
#6 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
#7 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
#8 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido.  in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\laragon\www\fotobook\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\fotobook\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\fotobook\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\fotobook\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
#5 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
#6 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
#7 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-10-16 15:23:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido. 
[Method: GET, Route: usuarios/2]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios_244321`
WHERE `usuarios_244321`.`id` = :usuarios_244321.id:', [...], false)
 3 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
 5 APPPATH\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-16 15:24:13 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido.  in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 187)
#1 C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('arturosaiza.com', 'ugsjwgu5z7wgt', 'guarache', 'dbhggkubvmugoy', 3306, '', 0)
#2 C:\laragon\www\fotobook\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\fotobook\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\laragon\www\fotobook\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\fotobook\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
#7 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
#8 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
#9 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#10 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido.  in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('arturosaiza.com', 'ugsjwgu5z7wgt', 'guarache', 'dbhggkubvmugoy', 3306, '', 0)
#1 C:\laragon\www\fotobook\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\fotobook\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\fotobook\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\fotobook\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
#6 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
#7 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
#8 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido.  in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\laragon\www\fotobook\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\fotobook\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\fotobook\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\fotobook\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
#5 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
#6 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
#7 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-10-16 15:24:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for arturosaiza.com failed: Host desconocido. 
[Method: GET, Route: usuarios/2]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios_244321`
WHERE `usuarios_244321`.`id` = :usuarios_244321.id:', [...], false)
 3 SYSTEMPATH\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(true, '2')
 5 APPPATH\Controllers\UsuarioController.php(30): CodeIgniter\BaseModel->find('2')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->show('2')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-16 15:59:50 --> mysqli_sql_exception: Duplicate entry 'samuelito@gmail.com' for key 'usuarios_244321.correo' in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\fotobook\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\fotobook\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\fotobook\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\fotobook\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\fotobook\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\fotobook\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
#10 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-10-16 15:59:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'samuelito@gmail.com' for key 'usuarios_244321.correo'
[Method: POST, Route: usuarios/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (:nombre:, :telefono:, :correo:, :password:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-16 15:59:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'samuelito@gmail.com' for key 'usuarios_244321.correo'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samuelito@gmail.com\', \'perico\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samuelito@gmail.com\', \'perico\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (:nombre:, :telefono:, :correo:, :password:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-16 15:59:50 --> [Caused by] mysqli_sql_exception: Duplicate entry 'samuelito@gmail.com' for key 'usuarios_244321.correo'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samuelito@gmail.com\', \'perico\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samuelito@gmail.com\', \'perico\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samuelito@gmail.com\', \'perico\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (:nombre:, :telefono:, :correo:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-10-16 16:00:46 --> mysqli_sql_exception: Duplicate entry '6224556878' for key 'usuarios_244321.telefono' in C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\laragon\www\fotobook\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 C:\laragon\www\fotobook\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\laragon\www\fotobook\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\laragon\www\fotobook\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\laragon\www\fotobook\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\fotobook\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\fotobook\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\fotobook\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\fotobook\app\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\fotobook\system\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
#10 C:\laragon\www\fotobook\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#11 C:\laragon\www\fotobook\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\fotobook\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 C:\laragon\www\fotobook\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\laragon\www\fotobook\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-10-16 16:00:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '6224556878' for key 'usuarios_244321.telefono'
[Method: POST, Route: usuarios/store]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (:nombre:, :telefono:, :correo:, :password:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-16 16:00:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '6224556878' for key 'usuarios_244321.telefono'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samaelito@gmail.com\', \'perico\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samaelito@gmail.com\', \'perico\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (:nombre:, :telefono:, :correo:, :password:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-10-16 16:00:46 --> [Caused by] mysqli_sql_exception: Duplicate entry '6224556878' for key 'usuarios_244321.telefono'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samaelito@gmail.com\', \'perico\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samaelito@gmail.com\', \'perico\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (\'Samuel\', \'6224556878\', \'samaelito@gmail.com\', \'perico\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios_244321` (`nombre`, `telefono`, `correo`, `password`) VALUES (:nombre:, :telefono:, :correo:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\UsuarioController.php(50): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->store()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
